/**
 * Build-time blog generation script
 * Generates a blog post during the build process to ensure content is available
 * Run during: npm run build (via package.json scripts)
 */

import { extractArticles } from '../lib/blog/extractor'
import { generateBlogPost } from '../lib/blog/generator'
import { factCheckBlogPost } from '../lib/blog/fact-checker'
import { saveBlogPost, generateSlug, blogPostExists } from '../lib/blog/storage'
import type { BlogPost } from '../lib/blog/types'
import { logger } from '../lib/logger'

async function generateBlogAtBuild() {
  console.log('📝 Starting build-time blog generation...\n')

  // Check required environment variables
  const requiredEnvVars = ['OPENROUTER_API_KEY', 'OPENROUTER_BLOG_MODEL', 'OPENROUTER_FACT_CHECK_MODEL']
  const missingVars = requiredEnvVars.filter((varName) => !process.env[varName])

  if (missingVars.length > 0) {
    console.warn('⚠️  Missing environment variables for blog generation:')
    missingVars.forEach((varName) => console.warn(`   - ${varName}`))
    console.warn('\n⚠️  Skipping blog generation at build time.')
    console.warn('   Blog posts will be generated by the cron job instead.\n')
    process.exit(0) // Exit successfully - this is not a critical error
  }

  try {
    // Step 1: Extract articles
    console.log('📰 Extracting articles from last 48 hours...')
    const articles = await extractArticles()
    console.log(`   Found ${articles.length} accessibility articles\n`)

    if (articles.length === 0) {
      console.log('ℹ️  No articles found in the last 48 hours.')
      console.log('   This is normal - blog posts will be generated by the cron job when articles are available.\n')
      process.exit(0) // Exit successfully
    }

    // Step 2: Generate blog post
    console.log('✍️  Generating blog post...')
    const blogContent = await generateBlogPost(articles)
    console.log(`   ✅ Generated ${blogContent.length} characters\n`)

    // Extract title from content or generate one
    const titleMatch = blogContent.match(/^#\s+(.+)$/m)
    let title = titleMatch
      ? titleMatch[1]
      : `Accessibility News Roundup - ${new Date().toLocaleDateString('en-US', {
          month: 'long',
          day: 'numeric',
          year: 'numeric',
        })}`

    // Remove title from content if present
    const finalContent = titleMatch ? blogContent.replace(/^#\s+.+$/m, '').trim() : blogContent

    // Generate slug
    let slug = generateSlug(title)
    let slugCounter = 1
    while (await blogPostExists(slug)) {
      slug = `${generateSlug(title)}-${slugCounter}`
      slugCounter++
    }

    // Step 3: Fact-check
    console.log('🔍 Fact-checking blog post...')
    const factCheckResult = await factCheckBlogPost(finalContent, title)
    console.log(`   ${factCheckResult.verified ? '✅ Verified' : '⚠️  Needs Review'}\n`)

    // Step 4: Determine publishing status
    const autoPublish = process.env.BLOG_AUTO_PUBLISH === 'true'
    const isPublished = autoPublish && factCheckResult.verified

    // Step 5: Create blog post object
    const blogPost: BlogPost = {
      slug,
      title,
      content: finalContent,
      excerpt: finalContent.substring(0, 300).replace(/\n/g, ' ') + '...',
      publishedAt: new Date().toISOString(),
      generatedAt: new Date().toISOString(),
      sources: articles.map((article) => ({
        title: article.title,
        url: article.url,
        source: article.source,
      })),
      factCheckStatus: factCheckResult.verified ? 'verified' : 'needs_review',
      factCheckNotes: factCheckResult.notes,
      isPublished,
      tags: ['accessibility', 'wcag', 'news', 'roundup'],
    }

    // Step 6: Save blog post
    console.log('💾 Saving blog post...')
    await saveBlogPost(blogPost)
    console.log(`   ✅ Saved: ${slug}\n`)

    console.log('✅ Build-time blog generation completed successfully!')
    console.log(`   Blog post: ${slug}`)
    console.log(`   Status: ${isPublished ? 'Published' : 'Needs Review'}\n`)
  } catch (error) {
    console.error('❌ Build-time blog generation failed:', error)
    console.error('\n⚠️  This is not a critical error - the build will continue.')
    console.error('   Blog posts will be generated by the cron job instead.\n')
    // Don't fail the build - this is optional
    process.exit(0)
  }
}

// Run the generation
generateBlogAtBuild().catch((error) => {
  console.error('Fatal error:', error)
  process.exit(0) // Don't fail the build
})

